apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: evt
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: evt-backend:local
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: evt
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: http
