{{- $ca := genCA "evt-frontend-ca" 365 }}
{{- $cert := genSignedCert "localhost" (list "127.0.0.1") (list "localhost") 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: evt-frontend-tls
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "evt-app.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
