namespace: evt

frontend:
  image: docker.io/pixelpenguin31/evt-frontend
  tag: latest
  pullPolicy: Always
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

backend:
  image: docker.io/pixelpenguin31/evt-backend
  tag: latest
  pullPolicy: Always
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

service:
  nodePort: 30080
